### ISSUE TITLE
compilation error with go 1.3

### ISSUE THREAD

**Issue by kozyraki** [mesosphere/mesos-dns#134]
The latest version does not compile with go version 1.3. 

$ go version
go version go1.3 linux/amd64
$ godep go build -o main.go
# github.com/mesosphere/mesos-dns
./main.go:85: syntax error: unexpected range, expecting {
./main.go:89: syntax error: argument to go/defer must be function call
./main.go:92: non-declaration statement outside function body
./main.go:105: non-declaration statement outside function body
./main.go:106: syntax error: unexpected }
godep: go exit status 2
